#!/usr/bin/env python3
"""
Aggregate a week-XX.csv measurement file into GEO metrics.

Reads the weekly CSV (generated by generate_week.py, filled in by the operator)
and computes per-model + overall: mention rate, citation rate, avg citation
position, share of voice, and sentiment split. Prints a readable table and
optionally appends a row to dashboard.md.

Usage:
  python3 aggregate.py 1              # summarize week-01.csv
  python3 aggregate.py 1 --lever "Schema.org"   # include lever label in dashboard row
"""
import csv
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
MODELS = ["ChatGPT", "Gemini", "DeepSeek", "Grok", "Qwen"]


def truthy(v: str) -> bool:
    return str(v).strip().lower() in ("y", "yes", "1", "true")


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    flags = {a.lstrip("-") for a in sys.argv[1:] if a.startswith("--")}
    lever = None
    for a in sys.argv[1:]:
        if a.startswith("--lever="):
            lever = a.split("=", 1)[1]
    if not args:
        print("usage: aggregate.py <week_number> [--lever='Schema.org']", file=sys.stderr)
        return 2
    week = int(args[0])
    path = HERE / f"week-{week:02d}.csv"
    if not path.exists():
        print(f"!! {path} not found", file=sys.stderr)
        return 1

    rows = []
    with path.open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            rows.append(r)

    # only rows actually filled in (mentioned is set)
    filled = [r for r in rows if str(r.get("mentioned", "")).strip() != ""]
    total = len(filled)

    def stats(subset):
        n = len(subset)
        if n == 0:
            return {"n": 0, "mention": 0.0, "cite": 0.0, "pos": None, "sent": {}}
        mentioned = [r for r in subset if truthy(r.get("mentioned"))]
        cited = [r for r in subset if truthy(r.get("cited_with_link"))]
        positions = []
        for r in cited:
            p = str(r.get("citation_position", "")).strip()
            if p.isdigit():
                positions.append(int(p))
        sent = Counter(
            str(r.get("sentiment", "")).strip().lower() or "unknown"
            for r in mentioned
        )
        return {
            "n": n,
            "mention": 100.0 * len(mentioned) / n,
            "cite": 100.0 * len(cited) / n,
            "pos": (sum(positions) / len(positions)) if positions else None,
            "sent": dict(sent),
        }

    print(f"\n=== Week {week} — {total} filled rows ===\n")
    hdr = f"{'model':<12} {'rows':>5} {'mention%':>9} {'cite%':>7} {'avgpos':>7}"
    print(hdr)
    print("-" * len(hdr))
    per_model = {}
    for m in MODELS:
        s = stats([r for r in filled if r.get("model") == m])
        per_model[m] = s
        pos = f"{s['pos']:.1f}" if s['pos'] is not None else "-"
        print(f"{m:<12} {s['n']:>5} {s['mention']:>8.1f}% {s['cite']:>6.1f}% {pos:>7}")
    overall = stats(filled)
    pos = f"{overall['pos']:.1f}" if overall['pos'] is not None else "-"
    print("-" * len(hdr))
    print(f"{'OVERALL':<12} {overall['n']:>5} {overall['mention']:>8.1f}% {overall['cite']:>6.1f}% {pos:>7}")

    # share of voice: SunHestia mentions vs competitor mentions
    sun_ments = sum(1 for r in filled if truthy(r.get("mentioned")))
    comp_ments = Counter()
    for r in filled:
        for c in str(r.get("competitors_mentioned", "")).split(";"):
            c = c.strip()
            if c:
                comp_ments[c] += 1
    comp_total = sum(comp_ments.values())
    sov = (100.0 * sun_ments / (sun_ments + comp_total)) if (sun_ments + comp_total) else 0.0
    print(f"\nShare of voice (SunHestia vs named competitors): {sov:.1f}%")
    if comp_ments:
        print("  competitors seen:", ", ".join(f"{k}({v})" for k, v in comp_ments.most_common(8)))

    # mentioned prompts detail
    hits = [r for r in filled if truthy(r.get("mentioned"))]
    if hits:
        print(f"\nMentioned prompts ({len(hits)}):")
        for r in hits:
            print(f"  - {r.get('prompt_id')} / {r.get('model')}: cite={r.get('cited_with_link')} pos={r.get('citation_position')} sent={r.get('sentiment')}")
    else:
        print("\nNo mentions this week (expected for a brand-new, unindexed site).")

    # which prompts still blank
    blank = len(rows) - total
    if blank:
        print(f"\n({blank} of {len(rows)} rows still blank — fill more for fuller signal.)")

    print(f"\nMention rate (overall): {overall['mention']:.1f}%  |  Citation rate: {overall['cite']:.1f}%")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
